apiVersion: apps/v1
kind: Deployment
metadata:
  name: novaai-service
  labels:
    app: novaai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: novaai-service
  template:
    metadata:
      labels:
        app: novaai-service
    spec:
      containers:
      - name: novaai-service
        image: registry.cn-hangzhou.aliyuncs.com/novaai/novaai-server:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"