// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.11
// source: proto/na_interface/service.proto

package na_interface

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_na_interface_service_proto protoreflect.FileDescriptor

const file_proto_na_interface_service_proto_rawDesc = "" +
	"\n" +
	" proto/na_interface/service.proto\x12\fna_interface\x1a$proto/na_interface/annotations.proto\x1a proto/na_interface/weather.proto2\xdb\x01\n" +
	"\rNovaAIService\x12\\\n" +
	"\vHealthCheck\x12\x1b.weather.HealthCheckRequest\x1a\x1c.weather.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12l\n" +
	"\x12GetTomorrowWeather\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/weather/tomorrow/{city}B\x17Z\x15internal/na_interfaceb\x06proto3"

var file_proto_na_interface_service_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: weather.HealthCheckRequest
	(*WeatherRequest)(nil),      // 1: weather.WeatherRequest
	(*HealthCheckResponse)(nil), // 2: weather.HealthCheckResponse
	(*WeatherResponse)(nil),     // 3: weather.WeatherResponse
}
var file_proto_na_interface_service_proto_depIdxs = []int32{
	0, // 0: na_interface.NovaAIService.HealthCheck:input_type -> weather.HealthCheckRequest
	1, // 1: na_interface.NovaAIService.GetTomorrowWeather:input_type -> weather.WeatherRequest
	2, // 2: na_interface.NovaAIService.HealthCheck:output_type -> weather.HealthCheckResponse
	3, // 3: na_interface.NovaAIService.GetTomorrowWeather:output_type -> weather.WeatherResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_na_interface_service_proto_init() }
func file_proto_na_interface_service_proto_init() {
	if File_proto_na_interface_service_proto != nil {
		return
	}
	file_proto_na_interface_weather_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_na_interface_service_proto_rawDesc), len(file_proto_na_interface_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_na_interface_service_proto_goTypes,
		DependencyIndexes: file_proto_na_interface_service_proto_depIdxs,
	}.Build()
	File_proto_na_interface_service_proto = out.File
	file_proto_na_interface_service_proto_goTypes = nil
	file_proto_na_interface_service_proto_depIdxs = nil
}
