// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.11
// source: proto/na_interface/weather.proto

package na_interface

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"` // 城市名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_proto_na_interface_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_na_interface_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_proto_na_interface_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// 响应消息
type WeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   string                 `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`              // 温度
	Condition     string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`                  // 天气状况
	Humidity      string                 `protobuf:"bytes,3,opt,name=humidity,proto3" json:"humidity,omitempty"`                    // 湿度
	WindSpeed     string                 `protobuf:"bytes,4,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"` // 风速
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherResponse) Reset() {
	*x = WeatherResponse{}
	mi := &file_proto_na_interface_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherResponse) ProtoMessage() {}

func (x *WeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_na_interface_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherResponse.ProtoReflect.Descriptor instead.
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return file_proto_na_interface_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherResponse) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *WeatherResponse) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *WeatherResponse) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

func (x *WeatherResponse) GetWindSpeed() string {
	if x != nil {
		return x.WindSpeed
	}
	return ""
}

var File_proto_na_interface_weather_proto protoreflect.FileDescriptor

const file_proto_na_interface_weather_proto_rawDesc = "" +
	"\n" +
	" proto/na_interface/weather.proto\x12\aweather\x1a$proto/na_interface/annotations.proto\"$\n" +
	"\x0eWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"\x8c\x01\n" +
	"\x0fWeatherResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\tR\vtemperature\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\tR\bhumidity\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x04 \x01(\tR\twindSpeed2~\n" +
	"\x0eWeatherService\x12l\n" +
	"\x12GetTomorrowWeather\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/weather/tomorrow/{city}B\x0fZ\rweather/protob\x06proto3"

var (
	file_proto_na_interface_weather_proto_rawDescOnce sync.Once
	file_proto_na_interface_weather_proto_rawDescData []byte
)

func file_proto_na_interface_weather_proto_rawDescGZIP() []byte {
	file_proto_na_interface_weather_proto_rawDescOnce.Do(func() {
		file_proto_na_interface_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_na_interface_weather_proto_rawDesc), len(file_proto_na_interface_weather_proto_rawDesc)))
	})
	return file_proto_na_interface_weather_proto_rawDescData
}

var file_proto_na_interface_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_na_interface_weather_proto_goTypes = []any{
	(*WeatherRequest)(nil),  // 0: weather.WeatherRequest
	(*WeatherResponse)(nil), // 1: weather.WeatherResponse
}
var file_proto_na_interface_weather_proto_depIdxs = []int32{
	0, // 0: weather.WeatherService.GetTomorrowWeather:input_type -> weather.WeatherRequest
	1, // 1: weather.WeatherService.GetTomorrowWeather:output_type -> weather.WeatherResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_na_interface_weather_proto_init() }
func file_proto_na_interface_weather_proto_init() {
	if File_proto_na_interface_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_na_interface_weather_proto_rawDesc), len(file_proto_na_interface_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_na_interface_weather_proto_goTypes,
		DependencyIndexes: file_proto_na_interface_weather_proto_depIdxs,
		MessageInfos:      file_proto_na_interface_weather_proto_msgTypes,
	}.Build()
	File_proto_na_interface_weather_proto = out.File
	file_proto_na_interface_weather_proto_goTypes = nil
	file_proto_na_interface_weather_proto_depIdxs = nil
}
