// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.11
// source: proto/na_interface/weather.proto

package na_interface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 天气请求消息
type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"` // 城市名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_proto_na_interface_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_na_interface_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_proto_na_interface_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// 天气响应消息
type WeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   string                 `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`              // 温度
	Humidity      string                 `protobuf:"bytes,2,opt,name=humidity,proto3" json:"humidity,omitempty"`                    // 湿度
	WindSpeed     string                 `protobuf:"bytes,3,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"` // 风速
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherResponse) Reset() {
	*x = WeatherResponse{}
	mi := &file_proto_na_interface_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherResponse) ProtoMessage() {}

func (x *WeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_na_interface_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherResponse.ProtoReflect.Descriptor instead.
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return file_proto_na_interface_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherResponse) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *WeatherResponse) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

func (x *WeatherResponse) GetWindSpeed() string {
	if x != nil {
		return x.WindSpeed
	}
	return ""
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_na_interface_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_na_interface_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_na_interface_weather_proto_rawDescGZIP(), []int{2}
}

// 健康检查响应
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务状态
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 服务版本
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 运行时间
	Uptime        int64 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_na_interface_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_na_interface_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_na_interface_weather_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

var File_proto_na_interface_weather_proto protoreflect.FileDescriptor

const file_proto_na_interface_weather_proto_rawDesc = "" +
	"\n" +
	" proto/na_interface/weather.proto\x12\aweather\"$\n" +
	"\x0eWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"n\n" +
	"\x0fWeatherResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\tR\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\tR\bhumidity\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x03 \x01(\tR\twindSpeed\"\x14\n" +
	"\x12HealthCheckRequest\"_\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptimeB\x17Z\x15internal/na_interfaceb\x06proto3"

var (
	file_proto_na_interface_weather_proto_rawDescOnce sync.Once
	file_proto_na_interface_weather_proto_rawDescData []byte
)

func file_proto_na_interface_weather_proto_rawDescGZIP() []byte {
	file_proto_na_interface_weather_proto_rawDescOnce.Do(func() {
		file_proto_na_interface_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_na_interface_weather_proto_rawDesc), len(file_proto_na_interface_weather_proto_rawDesc)))
	})
	return file_proto_na_interface_weather_proto_rawDescData
}

var file_proto_na_interface_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_na_interface_weather_proto_goTypes = []any{
	(*WeatherRequest)(nil),      // 0: weather.WeatherRequest
	(*WeatherResponse)(nil),     // 1: weather.WeatherResponse
	(*HealthCheckRequest)(nil),  // 2: weather.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: weather.HealthCheckResponse
}
var file_proto_na_interface_weather_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_na_interface_weather_proto_init() }
func file_proto_na_interface_weather_proto_init() {
	if File_proto_na_interface_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_na_interface_weather_proto_rawDesc), len(file_proto_na_interface_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_na_interface_weather_proto_goTypes,
		DependencyIndexes: file_proto_na_interface_weather_proto_depIdxs,
		MessageInfos:      file_proto_na_interface_weather_proto_msgTypes,
	}.Build()
	File_proto_na_interface_weather_proto = out.File
	file_proto_na_interface_weather_proto_goTypes = nil
	file_proto_na_interface_weather_proto_depIdxs = nil
}
